jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Update package database
        run: apt-get update -yqq
      - name: Upgrade packages
        run: apt-get upgrade -yqq
      - name: Install llvm
        run: apt-get install --no-install-recommends --reinstall -yqq llvm
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Create coverage reports
        run: make coverage
      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report-${{ github.event.repository.name }}
          path: fntt64.profile
name: Coverage
on:
  pull_request:
  push:
